### ISSUE TITLE
Undefined check missing in 5.0.0/5.0.1

### ISSUE THREAD

**Issue by struct78** [jonschlinkert/kind-of#13]
Hi,

This line requires an undefined check, the constructor's name property is undefined in IE11 and lower so it throws an exception when trying to call the slice method.

https://github.com/jonschlinkert/kind-of/blob/master/index.js#L32

**Comment by jonschlinkert** [comment]
want to do a pr?

**Comment by struct78** [comment]
Done https://github.com/jonschlinkert/kind-of/pull/14

**Comment by jonschlinkert** [comment]
forgot to close this, thanks again
