### ISSUE TITLE
add support for `Error` type?

### ISSUE THREAD

**Issue by ianstormtaylor** [jonschlinkert/kind-of#20]
Hey @jonschlinkert, awesome util!

Would you consider adding support for the native `Error` constructor checking, for an `'error'` type string?

**Comment by jonschlinkert** [comment]
> Would you consider adding support for the native Error constructor checking, for an 'error' type string?

Hey @ianstormtaylor, thanks! Do you mean something different [than the current error check](https://github.com/jonschlinkert/kind-of/blob/master/index.js#L77-L79)? I'm open to anything that will improve the lib if you want to do a PR.

**Comment by ianstormtaylor** [comment]
Ah wow I'm dumb, I read the readme and assumed it wasn't there. Just added a PR for the readme addition. Thank you!

**Comment by jonschlinkert** [comment]
Not your fault! You shouldn't have to read the code to figure that out, thanks for the PR!
