### ISSUE TITLE
Checking "typeof Buffer" causes browserify to bundle buffer package

### ISSUE THREAD

**Issue by ksheedlo** [jonschlinkert/kind-of#9]
Rel substack/node-browserify#1228

I found this code, which causes browserify to bundle the `buffer` package:

```js
if (typeof Buffer !== 'undefined' && isBuffer(val)) {
  return 'buffer';
}
```

The check for `typeof Buffer !== 'undefined'` is unnecessary since `is-buffer` already works fine in environments where `Buffer` is not defined. Removing it will prevent `kind-of` from causing this package (which pulls in a lot of code) to bloat the consumer's bundle.

**Comment by jonschlinkert** [comment]
published and tagged as 3.2.0. thanks again!
